---
- name: add oracle java repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: install java
  apt: name=oracle-java8-installer state=present

- name: install elasticsearch key
  apt_key: url='http://packages.elasticsearch.org/GPG-KEY-elasticsearch'

- name: add elasticsearch repo
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' update_cache=yes

- name: install elasticsearch
  apt: name=elasticsearch force=yes

- name: bind localhost
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp="network.bind_host:"
    line="network.bind_host: localhost"

- name: cors
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="http.cors.enabled: true"

- name: cors
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="http.cors.allow-origin: *"

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
