---
- name: add oracle java repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: install java
  apt: name=oracle-java8-installer state=present

- name: add elasticsearch repo
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main'

- name: install elasticsearch
  apt: name=elasticsearch update_cache=yes
