---
- name: install graphite
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - graphite-web
    - graphite-carbon
    - postgresql
    - libpq-dev
    - python-psycopg2
    - apache2
    - libapache2-mod-wsgi

- name: create db
  postgresql_db: name={{ graphite_db }}
  sudo: yes
  sudo_user: postgres

- name: create db user
  postgresql_user: db={{ graphite_db }} name={{ graphite_db_user }} password={{ graphite_db_pass }}
  sudo: yes
  sudo_user: postgres

- name: graphite local_settings template
  template: >
    src=local_settings.py
    dest=/etc/graphite/local_settings.py
    owner=root
    group=root
    mode=0644

- name: sync graphite db
  shell: "graphite-manage syncdb"
  sudo: yes

- name: enable carbon
  lineinfile: >
    dest=/etc/default/graphite-carbon
    regexp="CARBON_CACHE_ENABLED="
    line="CARBON_CACHE_ENABLED=true"

- name: enable carbon logrotation
  lineinfile: >
    dest=/etc/carbon/carbon.conf
    regexp="ENABLE_LOGROTATION ="
    line="ENABLE_LOGROTATION = True"

- name: carbon storage schemas
  template: >
    src=storage-schemas.conf
    dest=/etc/carbon/storage-schemas.conf
    owner=root
    group=root
    mode=0644

- name: carbon agregation schemas
  template: >
    src=storage-aggregation.conf
    dest=/etc/carbon/storage-aggregation.conf
    owner=root
    group=root
    mode=0644

- name: start carbon-cache
  service: name=carbon-cache state=started

- name: install graphite vhost
  template: >
    src=graphite.conf
    dest=/etc/apache2/sites-available
    owner=root
    group=root
    mode=0644

- name: enable graphite vhost
  shell: "a2ensite apache2-graphite"
  sudo: yes

- name: disable default apache vhost
  shell: "a2dissite 000-default"
  sudo: yes

- name: enable headers mod
  shell: "a2enmod headers"

- name: reload apache
  service: name=apache2 state=reloaded